#!/bin/bash

brew install autoconf
brew install automake
brew install bison
brew install cabextract
brew install cmake
brew install cmatrix
brew install colordiff
brew install coreutils
brew install enca
brew install fontconfig
brew install freetype
brew install fzf
brew install gcc
brew install gd
brew install gdbm
brew install gettext
brew install gflags
brew install glog
brew install gmp
brew install graphviz
brew install htop
brew install icu4c
brew install isl
brew install jpeg
brew install libevent
brew install libidn2
brew install libmpc
brew install libpng
brew install libtiff
brew install libtool
brew install libunistring
brew install lua
brew install mpfr
brew install mycli
brew install ncurses
brew install node
brew install openssl
brew install p7zip
brew install pcre
brew install pcre2
brew install python
brew install python@2
brew install readline
brew install sqlite
brew install the_silver_searcher
brew install tmux
brew install unrar
brew install webp
brew install wget
brew install wine
brew install winetricks
brew install xz
brew install youtube-dl
brew install zeromq
brew install zsh
brew install zsh-syntax-highlighting
